owner: KomplettNettbutikk
repo: status

sites:
  - name: KomplettNettbutikk.no
    url: https://www.komplettnettbutikk.no
  - name: Registrering
    url: $REGISTER_URL
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: KomplettNettbutikk Status
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: KomplettNettbutikk.no
      href: https://www.komplettnettbutikk.no
    - title: Dokumentasjon
      href: https://dokumentasjon.komplettnettbutikk.no

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
